<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Assets\Scripts\Battle\*.cs" Exclude="..\Assets\Scripts\Battle\BattleCharacterFactory.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
